#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


log() {
  _fg=''
  [ "${1}" = "red" ] && _fg='\033[0;31m'
  [ "${1}" = "blue" ] && _fg='\033[0;34m'
  [ "${1}" = "green" ] && _fg='\033[0;32m'
  shift
  # shellcheck disable=SC2145
  echo -e "${_fg}>>> ${@}\033[0m"
}

cluster="${PIPELINE_CLUSTER}"


echo ${cluster}
log green "applying for cluster ${cluster}"
( set -x; kubectl config use-context "${cluster}" ) || { log red "no context found, skipping ${cluster}" && exit 1; }
log green "applying to namespace ${namespace}"
( set -x; k apply ./kubectl_deploy -n "${namespace}"