version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t hello-world-ruby .
      - deploy:
          name: Push application Docker image
          environment:
            GITHUB_TEAM_NAME_SLUG: cp-team
            APPLICATON_DEPLOY_NAME: myruby-app
            REPONAME: cp-poornima-dev-module
          command: |
            login="$(AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_MYRUBYAPP} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_MYRUBYAPP} aws ecr get-login --no-include-email)"
            ${login}

            docker tag hello-world-ruby "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPONAME}:myruby-app-1.0"
            docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPONAME}:myruby-app-1.0"

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag hello-world-ruby "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPONAME}:myruby-app-latest"
              docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPONAME}:myruby-app-latest"
            fi