version: 2
references:
  cloud_container: &cloud_container
    docker:
      - image: ${ECR_ENDPOINT}/cloud-platform/tools:circleci
        environment:
          GITHUB_TEAM_NAME_SLUG: family-justice
jobs:
  build_staging:
    machine: true
    steps:
      - checkout
      - run: docker build -t hello-world-ruby .
      - deploy:
          name: Push application Docker image
          environment:
            GITHUB_TEAM_NAME_SLUG: cp-team
            APPLICATON_DEPLOY_NAME: myruby-app
            REPONAME: cp-poornima-dev-module
          command: |
            login="$(AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_MYRUBYAPP} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_MYRUBYAPP} aws ecr get-login --no-include-email)"
            ${login}

            docker tag hello-world-ruby "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPONAME}:${CIRCLE_SHA1}"
            docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPONAME}:${CIRCLE_SHA1}"

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag hello-world-ruby "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPONAME}:myruby-app-latest"
              docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPONAME}:myruby-app-latest"
            fi
  deploy_staging:
    <<: *cloud_container
    steps:
      - checkout
      - run:
          name: kubectl use context
          command: |
          login="$(AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_MYRUBYAPP} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_MYRUBYAPP} aws ecr get-login --no-include-email)"
            ${login}
            setup-kube-auth
            kubectl config set-cluster ${K8S_CLUSTER_NAME} --certificate-authority=./ca.crt --server=https://api.${K8S_CLUSTER_NAME}
            kubectl config set-credentials circleci-dev --token=${K8S_TOKEN}
            kubectl config set-context ${K8S_CLUSTER_NAME} --cluster=${K8S_CLUSTER_NAME} --user=circleci-dev --namespace=${K8S_NAMESPACE}
            kubectl config use-context ${K8S_CLUSTER_NAME}
      - deploy:
          name: rolling update image to staging
          command: |
            kubectl set image -n ${K8S_NAMESPACE} \
                webapp="${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${REPONAME}:${CIRCLE_SHA1}"
            kubectl annotate -n ${K8S_NAMESPACE} \
                set image ${REPONAME}:${CIRCLE_SHA1} via CircleCI"
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build_staging
      - deploy_staging
