apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-rubyapp-ingress
  namespace: poornima-dev
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
spec:
  tls:
  - hosts:
    - poornima-rubyapp.apps.pk-test-9.cloud-platform.service.justice.gov.uk
  - hosts:
    - dev-pk.service.justice.gov.uk
    secretName: myruby-app-cert-secret
  rules:
  - host: poornima-rubyapp.apps.pk-test-9.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: rubyapp-service
          servicePort: 4567
