apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helmchart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "helmchart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "helmchart.fullname" . }}
    spec:
      containers:
        - app: {{ template "helmchart.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4567
