apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "helmchart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
spec:
  tls:
    - host: pk-uu.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
    - host: pk-uu.apps.live-1.cloud-platform.service.justice.gov.uk
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ template "helmchart.fullname" . }}
            servicePort: 4567