apiVersion: v1
kind: Service
metadata:
  name: helloworld-rubyapp-service
  labels:
    app: helloworld-rubyapp-service
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4567
      name: http
  selector:
    app: helloworld-rubyapp
