apiVersion: v1
kind: Service
metadata:
  name: {{ template "helmchart.fullname" . }}
  labels:
    app:  {{ template "helmchart.fullname" . }}
    chart: {{ template "helmchart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4567
      name: http
  selector:
    app: {{ template "helmchart.fullname" . }}
    release: {{ .Release.Name }}
