# version: 2
# references:
#   cloud_container: &cloud_container
#     docker:
#       - image: ${ECR_ENDPOINT}/cloud-platform/tools:circleci
#         aws_auth:
#           aws_access_key_id: $AWS_ACCESS_KEY_ID_MYRUBYAPP
#           aws_secret_access_key: $AWS_SECRET_ACCESS_KEY_MYRUBYAPP
#         environment:
#           GITHUB_TEAM_NAME_SLUG: family-justice
#           GITHUB_TEAM_MYAPP_NAME_SLUG: cp-team
#           APPLICATION_MYAPP_DEPLOY_NAME: myruby-app
#           MYAPP_REPONAME: cp-poornima-dev-module
# jobs:
#   build_staging:
#     machine: true
#     steps:
#       - checkout
#       - run: docker build -t hello-world-ruby .
#       - deploy:
#           name: Push application Docker image
#           environment:
#             GITHUB_TEAM_MYAPP_NAME_SLUG: cp-team
#             APPLICATON_MYAPP_DEPLOY_NAME: myruby-app
#             MYAPP_REPONAME: cp-poornima-dev-module
#           command: |
#             login="$(AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_MYRUBYAPP} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_MYRUBYAPP} aws ecr get-login --no-include-email)"
#             ${login}

#             docker tag hello-world-ruby "${ECR_ENDPOINT}/${GITHUB_TEAM_MYAPP_NAME_SLUG}/${MYAPP_REPONAME}:${CIRCLE_SHA1}"
#             docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_MYAPP_NAME_SLUG}/${MYAPP_REPONAME}:${CIRCLE_SHA1}"

#             if [ "${CIRCLE_BRANCH}" == "master" ]; then
#               docker tag hello-world-ruby "${ECR_ENDPOINT}/${GITHUB_TEAM_MYAPP_NAME_SLUG}/${MYAPP_REPONAME}:myruby-app-latest"
#               docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_MYAPP_NAME_SLUG}/${MYAPP_REPONAME}:myruby-app-latest"
#             fi
#   deploy_staging:
#     <<: *cloud_container
#     steps:
#       - checkout
#       - run:
#           name: kubectl use context
#           command: |
#             setup-kube-auth
#             kubectl config use-context staging
#       - deploy:
#           name: deploy to staging
#           command: |
#             export BUILD_DATE=$(date -Is) >> $BASH_ENV
#             source $BASH_ENV
#             kubectl set image -n poornima-dev \
#                     deployment/myruby-app \
#                     myruby-app="${ECR_ENDPOINT}/${GITHUB_TEAM_MYAPP_NAME_SLUG}/${MYAPP_REPONAME}:${CIRCLE_SHA1}"

# workflows:
#   version: 2
#   test-build-deploy:
#     jobs:
#       - build_staging
#       - deploy_staging:
#           requires:
#             - build_staging
